# Generated by Django 5.1.4 on 2025-04-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="tools",
        ),
    ]
