# Generated by Django 5.1.4 on 2025-05-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_remove_customuser_job_title_remove_customuser_role_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_verified",
            new_name="is_pro",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="description",
        ),
        migrations.AddField(
            model_name="customuser",
            name="tools",
            field=models.ManyToManyField(blank=True, to="users.tool"),
        ),
        migrations.AddField(
            model_name="tool",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
