# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0  # Specify your desired version of Black
    hooks:
      - id: black
        name: black
        language_version: python3

