# Generated by Django 5.1.4 on 2025-07-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cam_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="camera",
            old_name="added_on",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="camera_type",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="location",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="stream_url",
        ),
        migrations.AddField(
            model_name="camera",
            name="brand",
            field=models.CharField(
                choices=[
                    ("tuya", "Tuya"),
                    ("okam", "O-KAM Pro"),
                    ("unknown", "Unbekannt"),
                ],
                default="tuya",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("tuya", "Tuya Camera"),
                    ("okam", "O-KAM Pro Camera"),
                    ("other", "Andere"),
                ],
                default="tuya",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="ip_address",
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name="camera",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
