# Generated by Django 5.1.4 on 2025-07-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cam_manager", "0002_rename_added_on_camera_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="stream_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
