# Generated by Django 5.1.5 on 2025-01-20 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitäten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brechnungsgrundsatz', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AusführungSatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satz_nummer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HauptNebenMuskel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Körpertyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('körpertyp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Muskelgruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ÜbungenKrafttraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('bild_path', models.TextField(blank=True, null=True)),
                ('video_path', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AktivitätenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('dauer', models.FloatField(blank=True, null=True)),
                ('distanz', models.FloatField(blank=True, null=True)),
                ('puls', models.CharField(blank=True, max_length=50, null=True)),
                ('max_puls', models.IntegerField(blank=True, null=True)),
                ('höhenmeter', models.FloatField(blank=True, null=True)),
                ('aktivität', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.aktivitäten')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AusführungWid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gewicht', models.FloatField()),
                ('ausführung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.ausführungsatz')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField(blank=True, null=True)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('thema', models.CharField(blank=True, max_length=200, null=True)),
                ('datum', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gewicht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gewicht', models.FloatField()),
                ('datum', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KörperData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('körperfettanteil', models.FloatField(blank=True, null=True)),
                ('muskelmasse', models.FloatField(blank=True, null=True)),
                ('knochenmasse', models.FloatField(blank=True, null=True)),
                ('fettmenge', models.FloatField(blank=True, null=True)),
                ('wassermenge', models.FloatField(blank=True, null=True)),
                ('datum', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KörpertyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(blank=True, null=True)),
                ('körpertyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.körpertyp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trainingsplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('training_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.trainingroutine')),
            ],
        ),
        migrations.CreateModel(
            name='KrafttrainingInstanz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(blank=True, null=True)),
                ('trainingsplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.trainingsplan')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingsplanÜbungenKrafttraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.krafttraininginstanz')),
                ('übung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.übungenkrafttraining')),
            ],
        ),
        migrations.AddField(
            model_name='ausführungsatz',
            name='training_übung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.trainingsplanübungenkrafttraining'),
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('größe', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ÜbungenKrafttrainingMuskelgruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muskel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.hauptnebenmuskel')),
                ('übung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.übungenkrafttraining')),
            ],
        ),
    ]
