# Generated by Django 5.1.5 on 2025-01-22 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingsplanÜbung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainingsplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.trainingsplan')),
                ('übung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.übungenkrafttraining')),
            ],
        ),
    ]
