# Generated by Django 5.1.5 on 2025-01-22 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_trainingsplanübung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsplan',
            name='training_routine',
        ),
        migrations.AlterField(
            model_name='trainingsplanübungenkrafttraining',
            name='übung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.übungenkrafttraining'),
        ),
        migrations.CreateModel(
            name='Trainingsplan_TrainingRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.trainingroutine')),
            ],
        ),
    ]
