# Generated by Django 5.1.5 on 2025-01-22 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_remove_trainingsplan_training_routine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsplan_trainingroutine',
            name='trainingsplan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workout.trainingsplan'),
            preserve_default=False,
        ),
    ]
