# Generated by Django 5.1.5 on 2025-01-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_trainingsplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsplanübung',
            name='satz',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingsplanübung',
            name='wiederholung',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
