# Generated by Django 5.1.5 on 2025-01-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_trainingsplanübung_satz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsplanübung',
            name='satz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsplanübung',
            name='wiederholung',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
