# Generated by Django 5.1.4 on 2024-12-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
