# Generated by Django 5.1.4 on 2025-04-18 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_hunter", "0004_alter_application_offer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pinfo",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="pinfo",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="pinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
