# Generated by Django 5.1.4 on 2025-04-18 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "job_hunter",
            "0005_remove_pinfo_first_name_remove_pinfo_last_name_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="pinfo",
            name="email",
            field=models.EmailField(default="no@email.given", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pinfo",
            name="first_name",
            field=models.CharField(default="no_first_name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pinfo",
            name="last_name",
            field=models.CharField(default="no_last_name", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pinfo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pinfo",
            name="tools",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_with_access",
                to="job_hunter.tool",
            ),
        ),
    ]
