# Generated by Django 5.1.4 on 2025-04-18 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "job_hunter",
            "0006_tool_pinfo_email_pinfo_first_name_pinfo_last_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pinfo",
            name="tools",
        ),
    ]
