# Generated by Django 5.1.4 on 2025-04-18 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunter", "0007_remove_pinfo_tools"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="about",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="offer",
        ),
        migrations.AddField(
            model_name="offer",
            name="about_company",
            field=models.TextField(default="ABOUT"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offer",
            name="offer_text",
            field=models.TextField(default="OFFERTEXTR"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="offer",
            name="url",
            field=models.URLField(default="URL"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="offer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
