# Generated by Django 5.1.4 on 2025-05-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_hunter",
            "0008_remove_offer_about_remove_offer_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlog",
            name="is_summary",
            field=models.BooleanField(default=False),
        ),
    ]
