import sqlite3
import os
# dynmischer code damit der standpunkt der ausführung egal ist. 
# für dummy daten hatte ein fehler, weshalb ich hier was geändert habe aber es hatte davo funktioniert
# daher ist der code nicht funktionsfähig. (lass den erst mal, weil ich das hier noch
# erweitere wegen paar andere daten. )

oberschenkel_uebungen = [
    "Squats",
    "Bulgarian Split Squats",
    "Lunges",
    "Reverse Lunges",
    "Lateral Lunges",
    "Step-Ups",
    "Box Jumps",
    "Sumo Squats",
    "Pistol Squats",
    "Goblet Squats",
    "Romanian Deadlifts",
    "Stiff-Leg Deadlifts",
    "Hamstring Curls (Machine)",
    "Leg Press",
    "Front Squats",
    "Jefferson Squats",
    "Zercher Squats",
    "Cable Kickbacks",
    "Glute Bridges",
    "Hip Thrusts",
    "Standing Calf Raises",
    "Seated Calf Raises",
    "Wall Sits",
    "Frog Pumps",
    "Clamshells",
    "Lying Leg Curls (Machine)",
    "Cable Lateral Lunges",
    "Hack Squats",
    "Sissy Squats",
    "Weighted Step-Ups",
    "Barbell Squats",
    "Split Squats (Dumbbells)",
    "Weighted Walking Lunges",
    "Jump Squats",
    "Band Resisted Squats",
    "Single-Leg Romanian Deadlifts",
    "Hip Abduction (Machine)",
    "Hip Adduction (Machine)",
    "Deadlifts",
    "Trap Bar Deadlifts",
    "Plyometric Lunges",
    "Reverse Step-Ups",
    "Curtsy Lunges",
    "Dumbbell Deadlifts",
    "Kettlebell Swings",
    "Glute-Ham Raises",
    "Cable Squats",
    "Swiss Ball Hamstring Curls",
    "Sumo Deadlifts",
    "Good Mornings",
    "Static Lunges"
]

waden_uebungen = [
    "Standing Calf Raises",
    "Seated Calf Raises",
    "Donkey Calf Raises",
    "Smith Machine Calf Raises",
    "Single-Leg Standing Calf Raises",
    "Weighted Step-Ups (Focus on Ball of Foot)",
    "Farmer's Walk on Toes",
    "Jump Rope",
    "Plyometric Calf Jumps",
    "Box Jumps (Focus on Calf Engagement)",
    "Tibialis Anterior Raises",
    "Calf Press on Leg Press Machine",
    "Running Uphill",
    "Sled Pushes",
    "Isometric Calf Hold",
    "Stair Climbing on Toes",
    "Incline Walking on Treadmill",
    "Jump Squats with Calf Focus",
    "Explosive Toe Raises",
    "Sand Walking"
]

brust_uebungen = [
    "Flat Bench Press",
    "Incline Bench Press",
    "Decline Bench Press",
    "Dumbbell Bench Press",
    "Incline Dumbbell Bench Press",
    "Decline Dumbbell Bench Press",
    "Push-Ups",
    "Incline Push-Ups",
    "Decline Push-Ups",
    "Wide Grip Push-Ups",
    "Close Grip Push-Ups",
    "Chest Dips",
    "Weighted Chest Dips",
    "Machine Chest Press",
    "Incline Machine Chest Press",
    "Decline Machine Chest Press",
    "Pec Deck Machine",
    "Cable Crossovers",
    "Incline Cable Crossovers",
    "Low to High Cable Crossovers",
    "High to Low Cable Crossovers",
    "Flat Dumbbell Flyes",
    "Incline Dumbbell Flyes",
    "Decline Dumbbell Flyes",
    "Machine Flyes",
    "Landmine Press",
    "Svend Press",
    "Hex Press",
    "Floor Press",
    "Clapping Push-Ups",
    "Archer Push-Ups",
    "One-Arm Push-Ups",
    "Medicine Ball Push-Ups",
    "Incline Dumbbell Pullover",
    "Flat Dumbbell Pullover",
    "Single-Arm Cable Flyes",
    "Incline Smith Machine Press",
    "Flat Smith Machine Press",
    "Decline Smith Machine Press",
    "Resistance Band Flyes",
    "Resistance Band Press",
    "Isometric Chest Hold (Bands)",
    "Bodyweight Chest Squeeze",
    "Kettlebell Floor Press",
    "Kettlebell Flyes",
    "Kettlebell Squeeze Press",
    "Weighted Push-Ups",
    "Deficit Push-Ups",
    "Incline Medicine Ball Press",
    "Decline Medicine Ball Press",
    "Dumbbell Crush Press",
    "Incline Barbell Press",
    "Decline Barbell Press",
    "Cable Chest Press",
    "Chest Press on Stability Ball",
    "Incline Chest Press on Stability Ball",
    "Explosive Bench Press",
    "Plyometric Push-Ups",
    "Feet-Elevated Push-Ups",
    "One-Arm Dumbbell Press",
    "Incline Single-Arm Dumbbell Press",
    "Resistance Band Push-Ups",
    "Suspension Trainer Push-Ups (TRX)",
    "TRX Flyes",
    "Chest Press with Chains",
    "Dumbbell Flyes on Stability Ball",
    "Incline Hex Press",
    "Decline Hex Press",
    "Medicine Ball Flyes",
    "Crossover Push-Ups",
    "Weighted Plyometric Push-Ups",
    "Incline Dumbbell Crush Press",
    "Flat Dumbbell Crush Press",
    "Guillotine Bench Press",
    "Incline Guillotine Bench Press",
    "Band Resisted Bench Press",
    "Reverse Grip Bench Press",
    "Incline Reverse Grip Bench Press",
    "Flat Reverse Grip Dumbbell Press",
    "Chest Press with Resistance Bands and Dumbbells",
    "Decline Reverse Grip Bench Press",
    "Incline Kettlebell Squeeze Press",
    "Explosive Incline Push-Ups",
    "Sliding Push-Ups",
    "Weighted Chest Flyes (Machine)",
    "Incline Sliding Push-Ups",
    "Neutral Grip Dumbbell Press",
    "Incline Neutral Grip Dumbbell Press",
    "Deficit Wide Grip Push-Ups",
    "Low Cable Chest Squeeze",
    "Incline Low Cable Chest Squeeze",
    "Incline Barbell Guillotine Press",
    "Incline Plyometric Push-Ups",
    "Decline Plyometric Push-Ups",
    "Chest Squeeze with Medicine Ball",
    "Dumbbell Flyes with Resistance Bands",
    "Incline Dumbbell Flyes with Resistance Bands",
    "Flat Barbell Press with Chains",
    "Decline Barbell Press with Chains",
    "Incline Dumbbell Press with Bands"
]

trizeps_uebungen = [
    "Close Grip Bench Press",
    "Skull Crushers (EZ Bar)",
    "Overhead Dumbbell Extension",
    "One-Arm Overhead Dumbbell Extension",
    "Tricep Pushdowns (Cable)",
    "Reverse Grip Tricep Pushdowns (Cable)",
    "Rope Tricep Pushdowns (Cable)",
    "Overhead Tricep Rope Extension",
    "Bench Dips",
    "Weighted Bench Dips",
    "Parallel Bar Dips",
    "Weighted Parallel Bar Dips",
    "Kickbacks (Dumbbell)",
    "One-Arm Kickbacks (Dumbbell)",
    "Incline Dumbbell Kickbacks",
    "Close Grip Push-Ups",
    "Diamond Push-Ups",
    "Tricep Extensions (EZ Bar)",
    "Incline Skull Crushers",
    "Decline Skull Crushers",
    "French Press (Dumbbell)",
    "French Press (EZ Bar)",
    "Lying Tricep Extensions (Barbell)",
    "Seated Overhead Tricep Press",
    "Standing Overhead Tricep Press (Barbell)",
    "One-Arm Overhead Cable Extension",
    "Rope Overhead Cable Extension",
    "Reverse Grip Bench Press",
    "Incline Close Grip Bench Press",
    "Decline Close Grip Bench Press",
    "Smith Machine Close Grip Bench Press",
    "Dumbbell Close Grip Bench Press",
    "Push-Up Holds (Tricep Focus)",
    "Tricep Kickbacks with Resistance Band",
    "Cable One-Arm Tricep Kickbacks",
    "Reverse Grip Tricep Kickbacks (Cable)",
    "Single-Arm Dumbbell Overhead Extension",
    "Overhead Kettlebell Tricep Extension",
    "Incline Dumbbell Overhead Extension",
    "Decline Dumbbell Overhead Extension",
    "Close Grip Dumbbell Press",
    "Bodyweight Tricep Extensions",
    "Wall Tricep Extensions",
    "TRX Tricep Extensions",
    "Rope Tricep Kickbacks (Cable)",
    "Tricep Bench Holds",
    "Rope Pressdowns with Hold",
    "Incline Push-Ups with Tricep Focus",
    "Decline Push-Ups with Tricep Focus",
    "Explosive Tricep Push-Ups",
    "Weighted Diamond Push-Ups",
    "Close Grip Dumbbell Flyes",
    "Kettlebell Close Grip Press",
    "Band Resisted Push-Ups",
    "Band Resisted Dips",
    "Incline Dumbbell Tricep Extensions",
    "Decline Dumbbell Tricep Extensions",
    "Incline Rope Tricep Extensions (Cable)",
    "Decline Rope Tricep Extensions (Cable)",
    "Cross-Body Tricep Extensions (Cable)",
    "Underhand Rope Tricep Pushdowns",
    "Reverse Grip Single-Arm Pushdowns",
    "EZ Bar Close Grip Press",
    "Dumbbell Rolling Tricep Extensions",
    "Dumbbell Floor Press (Tricep Focus)",
    "Isometric Hold Tricep Pushdowns",
    "Incline Barbell Skull Crushers",
    "Close Grip Floor Press",
    "Ring Dips",
    "Weighted Ring Dips",
    "Kettlebell Kickbacks",
    "Kettlebell Tricep Press",
    "Pushdowns with Chains",
    "Barbell Tricep Extensions",
    "Seated Machine Tricep Pushdowns",
    "Overhead Machine Tricep Extensions",
    "Rope Tricep Squeeze Pushdowns",
    "Incline Cable Overhead Tricep Extensions",
    "Barbell Tricep Kickbacks",
    "Dumbbell Pullover to Press (Tricep Focus)",
    "Incline Tricep Rope Pressdowns",
    "Incline Close Grip Dumbbell Press",
    "Explosive Rope Pushdowns",
    "Isometric Rope Holds",
    "Dumbbell Cross-Body Kickbacks",
    "Kettlebell Close Grip Push-Ups",
    "Incline Weighted Tricep Dips",
    "Explosive Tricep Bench Press",
    "Band Kickbacks",
    "Overhead Tricep Holds (Cable)",
    "Barbell Close Grip Press with Chains",
    "Incline Tricep Press Machine",
    "Decline Tricep Press Machine",
    "Weighted Incline Push-Ups",
    "Weighted Decline Push-Ups",
    "Band Skull Crushers",
    "Sled Push (Tricep Focus)"
]

schulter_uebungen = [
    "Overhead Press (Barbell)",
    "Dumbbell Shoulder Press",
    "Arnold Press",
    "Standing Military Press",
    "Seated Military Press",
    "Push Press",
    "Z-Press",
    "Dumbbell Lateral Raises",
    "Cable Lateral Raises",
    "Front Raises (Dumbbell)",
    "Barbell Front Raise",
    "Cable Front Raises",
    "Reverse Flyes (Dumbbell)",
    "Reverse Cable Flyes",
    "Face Pulls (Cable)",
    "Upright Rows (Barbell)",
    "Upright Rows (Dumbbell)",
    "Cable Upright Rows",
    "Lateral Raises with Dumbbells (Single Arm)",
    "Bent-Over Lateral Raises (Dumbbell)",
    "Dumbbell Shrugs",
    "Barbell Shrugs",
    "Kettlebell Shrugs",
    "Face Pulls with Rope (Cable)",
    "Cable Internal Shoulder Rotation",
    "Cable External Shoulder Rotation",
    "Dumbbell Incline Lateral Raises",
    "Landmine Shoulder Press",
    "Landmine Lateral Raises",
    "Overhead Dumbbell Press",
    "Single-Arm Overhead Dumbbell Press",
    "Kettlebell Shoulder Press",
    "Kettlebell Front Raise",
    "Kettlebell Lateral Raise",
    "Plate Raise",
    "Dumbbell Crossbody Lateral Raise",
    "Seated Lateral Raise Machine",
    "Seated Shoulder Press Machine",
    "Barbell Overhead Shrug",
    "Chest-Supported Reverse Flyes",
    "Dumbbell Front Raise with Rotation",
    "Machine Shoulder Press",
    "Smith Machine Shoulder Press",
    "Lateral Raise with Resistance Bands",
    "Overhead Cable Extensions (Single Arm)",
    "Kettlebell Turkish Get-Ups",
    "Isometric Lateral Raise Hold",
    "Machine Lateral Raise",
    "Cable Face Pulls with Rope",
    "Dumbbell Military Press",
    "Incline Front Raise",
    "Dumbbell Cuban Press",
    "Bent-Over Dumbbell Reverse Fly",
    "Overhead Barbell Press",
    "Triceps Push-Up (Focus on Shoulders)",
    "Cable Shoulder Press",
    "Reverse Pec Deck Machine",
    "Single-Arm Cable Lateral Raises",
    "Dumbbell Rotator Cuff Exercise",
    "Shoulder Isolation Press",
    "Dumbbell Rear Delt Raise",
    "Inverted Shoulder Press",
    "Standing Cable Shoulder Press",
    "Cable Rear Delt Fly",
    "Band Lateral Raise",
    "Lateral Raise Machine",
    "Front Raise with Resistance Bands",
    "Kettlebell Lateral Raise (Single Arm)",
    "Wide-Grip Upright Row",
    "Wide-Grip Dumbbell Upright Row",
    "Incline Dumbbell Shoulder Press",
    "Cable Reverse Fly",
    "Machine Shrugs",
    "Barbell Reverse Flyes",
    "Machine Shoulder Shrug",
    "Dumbbell Front Raise with Hold",
    "Barbell Cuban Press",
    "Arnold Press with Dumbbells",
    "Incline Dumbbell Reverse Flyes",
    "Incline Cable Face Pulls",
    "Dumbbell Shoulder Complex",
    "Dumbbell High Pulls",
    "Overhead Resistance Band Press",
    "Lateral Raise with Dumbbells (Both Arms)",
    "Front Plate Raise",
    "Behind-the-Neck Shoulder Press",
    "Incline Cable Lateral Raise",
    "Dumbbell Lateral Raise with Hold",
    "Dumbbell Crossbody Rear Delt Fly",
    "Seated Barbell Shoulder Press",
    "Machine Chest Fly (Shoulder Focus)",
    "Bent-Over Lateral Raise Machine",
    "Smith Machine Shoulder Shrug",
    "Kettlebell Snatches",
    "Kettlebell Swing",
    "Front Dumbbell Raise with Twist",
    "Barbell Shoulder Raise",
    "TRX Shoulder Taps",
    "TRX Y Raise",
    "Dumbbell Shoulder Press with Hold",
    "Face Pull with Rope and Hold",
    "Dumbbell Shrugs with Hold",
    "Overhead Lateral Raise with Bands",
    "Single-Arm Cable Front Raise",
    "Band Face Pulls",
    "Machine Front Raise",
    "Barbell Cuban Rotation",
    "Band Overhead Press",
    "Single-Arm Cable Shoulder Press",
    "Kettlebell Shoulder Raise",
    "Isometric Lateral Raise with Dumbbells",
    "Standing Lateral Raise with Kettlebell",
    "One-Arm Front Raise with Dumbbell",
    "Kettlebell Push Press",
    "Resistance Band Overhead Shoulder Press",
    "Barbell Shoulder Raise with Plate",
    "Cable Overhead Lateral Raise",
    "Machine Shoulder Lateral Raise",
    "Rotator Cuff Exercise (Cable)",
    "Single-Arm Lateral Raise with Bands",
    "Seated Front Raise",
    "Machine Lateral Raise with Hold",
    "Crossbody Cable Lateral Raise",
    "Dumbbell Arnold Press (Alternating)"
]

bizeps_uebungen = [
    "Barbell Bicep Curls",
    "Dumbbell Bicep Curls",
    "Hammer Curls (Dumbbell)",
    "Concentration Curls (Dumbbell)",
    "Incline Dumbbell Curls",
    "Preacher Curl (EZ Bar)",
    "Barbell Preacher Curl",
    "Machine Preacher Curl",
    "Spider Curl (Dumbbell)",
    "Cable Bicep Curl",
    "Cable Preacher Curl",
    "Resistance Band Bicep Curls",
    "Zottman Curls",
    "Reverse Grip Barbell Curl",
    "Reverse Grip Dumbbell Curl",
    "Reverse Cable Curls",
    "Drag Curls",
    "Close-Grip Barbell Curl",
    "Wide-Grip Barbell Curl",
    "EZ Bar Curl",
    "EZ Bar Reverse Curl",
    "Hammer Curl with Rope (Cable)",
    "Seated Dumbbell Curls",
    "Standing Dumbbell Curls",
    "Alternating Dumbbell Curls",
    "Single-Arm Dumbbell Curl",
    "Barbell Curl with Hold",
    "Machine Bicep Curl",
    "Cable Curl with Rope",
    "Dumbbell Curl with Twist",
    "Incline Hammer Curl",
    "EZ Bar Drag Curl",
    "Barbell Curl with Chains",
    "Dumbbell Preacher Curl",
    "Barbell Preacher Curl with Chains",
    "Overhead Cable Bicep Curl",
    "Cable Bicep Curl with Rope",
    "Concentration Curl with Resistance Band",
    "Kettlebell Bicep Curls",
    "Cable Curls with Single Arm",
    "Dumbbell Curl with Pause at Top",
    "Crossbody Dumbbell Curl",
    "Machine Curl with Single Arm",
    "Dumbbell Alternating Hammer Curl",
    "Kettlebell Hammer Curl",
    "Cable Drag Curl",
    "Wide-Grip EZ Bar Curl",
    "Barbell Bicep Curl with Squeeze",
    "Bicep Curl with Dumbbells (Alternating)",
    "Hammer Curl with Dumbbell Hold",
    "Alternating Hammer Curl with Rope (Cable)",
    "Barbell Curl with Tension",
    "Seated Preacher Curl (EZ Bar)",
    "EZ Bar Close-Grip Curl",
    "Machine Hammer Curl",
    "Cable Hammer Curl",
    "Incline EZ Bar Curl",
    "Cable Curl (Single Arm)",
    "Decline Dumbbell Curl",
    "Kettlebell Curl with Twist",
    "TRX Bicep Curl",
    "Concentration Curl with Dumbbell and Hold",
    "Spider Curl (EZ Bar)",
    "Bicep Curl with Medicine Ball",
    "Reverse Dumbbell Curl with Hold",
    "Barbell Curl with Isometric Hold",
    "Dumbbell Curl with Resistance Bands",
    "Seated Alternating Dumbbell Curl",
    "Cable Curl with Overhead Grip",
    "Cross-Body Dumbbell Curl",
    "Band Assisted Bicep Curl",
    "Cable Curl with Single Arm and Hold",
    "Incline Dumbbell Curl with Hold",
    "Dumbbell Curl with Slow Eccentric",
    "Triceps Push-Up with Bicep Focus",
    "Dumbbell Curl to Shoulder Press",
    "Kettlebell Curl with Focused Eccentric",
    "Barbell Bicep Curl with Slow Eccentric",
    "Cable Curl with Pause",
    "Overhead Resistance Band Curl",
    "Dumbbell Curl with Full Range of Motion",
    "Standing Barbell Curl with Hold",
    "EZ Bar Bicep Curl with Full Squeeze",
    "Band Curl with Pause",
    "Incline Dumbbell Curl with Slow Eccentric",
    "Machine Curl with Resistance Bands",
    "Single-Arm Cable Curl with Hold",
    "Standing Cable Curl with Rope",
    "Cable Curl with Isometric Hold",
    "Dumbbell Curl to Concentration Curl",
    "Spider Curl on Machine",
    "Barbell Reverse Bicep Curl with Hold",
    "Resistance Band Preacher Curl",
    "Decline Barbell Curl",
    "Cable Bicep Curl with Squeeze",
    "Dumbbell Reverse Curl",
    "Hammer Curl to Reverse Curl",
    "Zottman Curl with Dumbbells",
    "Reverse Grip EZ Bar Curl",
    "Lying Barbell Curl",
    "TRX Reverse Curl",
    "Hammer Curl with Full Range of Motion",
    "Barbell Curl with Tension and Pause",
    "Incline Hammer Curl",
    "Overhead Dumbbell Curl",
    "Machine Reverse Curl",
    "Bicep Curl with Extended Range",
    "EZ Bar Curl with Pause at Peak",
    "Standing Machine Curl",
    "Wide-Grip Dumbbell Curl",
    "Concentration Curl with Full Range",
    "Crossbody Hammer Curl with Dumbbell",
    "EZ Bar Bicep Curl with Hold",
    "Single-Arm Resistance Band Curl",
    "Cross-Body Cable Curl",
    "Single-Arm Hammer Curl with Dumbbell",
    "Cable Curl with Pause and Hold"
]

ruecken_uebungen = [
    "Deadlift (Barbell)",
    "Romanian Deadlift (Barbell)",
    "Sumo Deadlift",
    "Stiff-Legged Deadlift",
    "Deadlift (Dumbbell)",
    "Rack Pulls",
    "Bent-Over Barbell Row",
    "Bent-Over Dumbbell Row",
    "Single-Arm Dumbbell Row",
    "Pendlay Row",
    "T-Bar Row",
    "Seated Cable Row",
    "Lat Pulldown",
    "Pull-Ups (Wide Grip)",
    "Pull-Ups (Close Grip)",
    "Assisted Pull-Ups",
    "Chin-Ups",
    "Machine Row",
    "Inverted Row",
    "Lat Pulldown (Wide Grip)",
    "Lat Pulldown (Reverse Grip)",
    "Chest-Supported Row",
    "Landmine Row",
    "Machine Lat Pulldown",
    "Reverse Grip Barbell Row",
    "Kettlebell Row",
    "Kettlebell Swing",
    "Barbell Shrugs",
    "Dumbbell Shrugs",
    "Kettlebell Shrugs",
    "Machine Shrug",
    "Cable Shrug",
    "Standing Cable Row",
    "Seated Lat Pulldown",
    "Standing One-Arm Dumbbell Row",
    "Seated One-Arm Row",
    "Cable Face Pulls",
    "Cable Reverse Fly",
    "Dumbbell Reverse Fly",
    "Cable Deadlifts",
    "Machine Chest-Supported Reverse Fly",
    "Hyperextensions",
    "Back Extensions (Machine)",
    "Back Extensions (Roman Chair)",
    "Good Mornings (Barbell)",
    "Good Mornings (Dumbbell)",
    "Kettlebell Good Mornings",
    "Wide-Grip Lat Pulldown",
    "Close-Grip Lat Pulldown",
    "Neutral Grip Pull-Ups",
    "Inverted Rows (Bodyweight)",
    "Resistance Band Lat Pulldown",
    "Dumbbell Pullover",
    "Barbell Pullover",
    "Cable Pullover",
    "Straight-Arm Lat Pulldown",
    "Renegade Rows",
    "Pull-Throughs (Cable)",
    "Cable Back Pull",
    "Machine Row (Hammer Grip)",
    "Seated Hammer Row",
    "Inverted Cable Row",
    "Single-Arm Lat Pulldown",
    "Kettlebell Deadlift",
    "Straight Leg Deadlift",
    "Trap Bar Deadlift",
    "Snatch-Grip Deadlift",
    "Single-Leg Romanian Deadlift",
    "Dumbbell Sumo Deadlift",
    "Hyperextension Hold",
    "Kettlebell Romanian Deadlift",
    "Pull-Up with Resistance Bands",
    "Chin-Up with Resistance Bands",
    "Bent-Over Reverse Fly",
    "Barbell Reverse Fly",
    "Machine Rear Delt Fly",
    "Cable Reverse Delt Fly",
    "Chest-Supported Row (Dumbbell)",
    "One-Arm Cable Row",
    "Barbell Row with Pause",
    "Underhand Barbell Row",
    "EZ Bar Row",
    "Landmine T-Bar Row",
    "Dumbbell Row with Rotation",
    "Seated Row with Pause",
    "Cable Seated Row with Rope",
    "Cable Rows with Pause",
    "Lat Pulldown (Underhand Grip)",
    "Wide-Grip Pull-Up",
    "Close-Grip Pull-Up",
    "Smith Machine Deadlift",
    "Roman Chair Hyperextension",
    "Bodyweight Good Mornings",
    "Barbell Back Extension",
    "Dumbbell Back Extension",
    "Resistance Band Deadlifts",
    "Deadlift (Trap Bar)",
    "Kettlebell Sumo Deadlift",
    "T-Bar Row with Plate",
    "Smith Machine Row",
    "Machine Lat Pulldown (Close Grip)",
    "Kettlebell Overhead Row",
    "Barbell High Pull",
    "Smith Machine Shrug",
    "Machine Pull-Through",
    "Lying Back Extensions",
    "Kettlebell Chest Supported Row",
    "One-Arm Lat Pulldown",
    "Reverse Pec Deck Machine",
    "Incline Dumbbell Row",
    "Seated Reverse Cable Fly",
    "Seated Dumbbell Row",
    "Resistance Band Back Extensions",
    "Kettlebell Single-Leg Deadlift",
    "Cable Row with Pause at Peak",
    "Chest-Supported T-Bar Row",
    "TRX Rows",
    "T-Bar Row (Single Arm)",
    "Kettlebell Row with Hold",
    "Band Assisted Pull-Ups",
    "Barbell Row with Iso Hold",
    "Dumbbell Chest-Supported Row",
    "Renegade Rows with Push-Up",
    "Cable Row to Neck",
    "Machine Chest Supported Row",
    "Overhead Cable Lat Pulldown",
    "Barbell Shrugs with Hold",
    "Kettlebell Renegade Rows",
    "Cable Renegade Rows",
    "Lat Pulldown with Hold",
    "Single-Arm Dumbbell Row with Pause",
    "Dumbbell Back Extension",
    "Low Row (Machine)",
    "Lying Cable Row",
    "Wide-Grip Barbell Row",
    "Cable Row to Chest",
    "Smith Machine Lat Pulldown",
    "Dumbbell Lateral Raise with Hold",
    "Barbell Curl (Row Variation)",
    "Seated Row with Rope",
    "Cable Row with Wide Grip",
    "Smith Machine Pull-Up",
    "Squat and Row with Dumbbells",
    "Pull-Up Machine",
    "Assisted Lat Pulldown Machine",
    "Machine Chest-Supported Reverse Fly",
    "Kettlebell High Pull",
    "Single-Leg Kettlebell Deadlift",
    "Single-Leg Dumbbell Row",
    "Dumbbell Back Raise",
    "Landmine Reverse Row",
    "One-Arm Chest-Supported Row",
    "Kettlebell Deadlift to Row",
    "Machine Back Extensions",
    "Cable Lat Pulldown with Hold",
    "Machine Deadlift",
    "Lateral Pulldown Machine",
    "Cable Machine Row",
    "Chest-Supported Machine Row",
    "Kettlebell Renegade Row with Push-Up",
    "Standing Resistance Band Row",
    "Dumbbell Row with Hold",
    "Machine Lat Pulldown (Wide Grip)",
    "Band Assisted Chin-Ups",
    "Single-Leg Resistance Band Deadlift",
    "Chest-Supported Reverse Row with Dumbbells",
    "Standing Barbell Row",
    "Single-Leg Cable Row",
    "Dumbbell Sumo Row",
    "T-Bar Row with Hammer Grip",
    "Cable Low Row",
    "Seated Machine Row",
    "Cable Reverse Lat Pulldown",
    "Kettlebell Front Squat and Row",
    "Smith Machine Deadlift with Pause",
    "Landmine Row with Squeeze",
    "Renegade Row with Kettlebell",
    "Machine Lat Pulldown (Underhand Grip)",
    "Kettlebell Front Squat to Row",
    "Seated Barbell Row",
    "Barbell Power Row",
    "Hammer Strength Machine Row",
    "Kettlebell Clean and Row",
    "Smith Machine T-Bar Row",
    "Dumbbell Row to Chest",
    "Back Extension with Resistance Band",
    "Kettlebell Deadlift with Pause",
    "Wide Grip Resistance Band Lat Pulldown",
    "Reverse Grip Cable Row",
    "Dumbbell Shrug to Row",
    "Smith Machine Shrug to Row",
    "Kettlebell Deadlift with Hold",
    "Romanian Deadlift with Dumbbells",
    "Single-Arm Kettlebell Row",
    "Barbell Row with Band Resistance",
    "Machine Lat Pulldown with Hold",
    "Barbell Shrug to Deadlift",
    "Cable High Row",
    "Cable Low Row with Pause",
    "Barbell Clean and Row",
    "Resistance Band Chest-Supported Row",
    "Bent-Over Reverse Cable Fly",
    "Single-Leg Machine Row",
    "Wide-Grip Cable Row",
    "One-Arm Resistance Band Row",
    "Seated Lat Pulldown with Rope",
    "Kettlebell Row with Pause",
    "Machine Row with Pause"
]

bauch_uebungen = [
    "Crunches",
    "Bicycle Crunches",
    "Reverse Crunches",
    "Leg Raises",
    "Plank",
    "Side Plank",
    "Russian Twists",
    "V-Situps",
    "Mountain Climbers",
    "Flutter Kicks",
    "Hanging Leg Raises",
    "Hanging Knee Raises",
    "Sit-Ups",
    "Decline Sit-Ups",
    "Decline Leg Raises",
    "Captain's Chair Leg Raise",
    "Cable Crunches",
    "Ab Wheel Rollouts",
    "Stability Ball Rollouts",
    "Kettlebell Russian Twists",
    "Side Crunches",
    "Lying Leg Raises",
    "V-Ups",
    "Oblique V-Ups",
    "Swiss Ball Crunches",
    "Cable Woodchoppers",
    "Leg Raise with Twist",
    "Scissor Kicks",
    "Alternating Toe Touches",
    "Plank with Leg Lift",
    "Jackknife Sit-Ups",
    "Toe Touch Crunches",
    "Standing Oblique Crunches",
    "Standing Leg Raise",
    "Cable Pallof Press",
    "Hollow Body Hold",
    "Side Plank with Hip Dips",
    "Standing Cable Crunches",
    "Lateral Leg Raises",
    "Plank with Shoulder Taps",
    "Ab Rollouts with Stability Ball",
    "Swiss Ball Jackknife",
    "Kettlebell Windmill",
    "Mountain Climbers with Twist",
    "Boat Pose",
    "Leg Raise with Reach",
    "Ab Crunch with Medicine Ball",
    "Kettlebell Russian Twist with Hold",
    "Weighted Sit-Ups",
    "Weighted Leg Raises",
    "Abdominal Plank",
    "Spider Plank",
    "Knee Tuck Crunches",
    "Straight Leg Raise with Hold",
    "Standing Bicycle Crunches",
    "Medicine Ball Slams",
    "Bicycle Sit-Ups",
    "Side Plank with Leg Lift",
    "Knee-In Crunches",
    "Medicine Ball Twist",
    "Side Plank with Knee Crunch",
    "Plank Reach Through",
    "Cable Reverse Crunches",
    "Weighted Russian Twists",
    "Mountain Climbers with Push-Up",
    "Sit-Up with Medicine Ball",
    "Single Leg Crunches",
    "Weighted Oblique Crunches",
    "Plank to Push-Up",
    "Russian Twist with Plate",
    "Leg Raise with Medicine Ball",
    "Lying Hip Thrusts",
    "Decline Bench Crunches",
    "Lying Russian Twists",
    "Ball Pass (Swiss Ball)",
    "Plank to Knee Tuck",
    "Ab Rollout with Barbell",
    "Crunches with Exercise Ball",
    "Leg Raise with Resistance Band",
    "Side-to-Side Leg Raises",
    "Lying Leg Raise with Band",
    "V-Up to Push-Up",
    "Side Plank Reach",
    "Crunch with Resistance Band",
    "Plank with Arm Lift",
    "Side Plank with Knee Tuck",
    "Mountain Climbers with Resistance Band",
    "Leg Raise with Twist and Hold",
    "Hanging Windshield Wipers",
    "Abdominal Hold",
    "Toe Touch Plank",
    "Resistance Band Side Crunch",
    "Kettlebell Sit-Up",
    "Ab Twist with Medicine Ball",
    "Windshield Wipers",
    "Plank with Knee Tap",
    "High Knee Sit-Ups",
    "Single-Leg Plank",
    "Barbell Rollouts",
    "Lying Alternating Leg Raise",
    "Standing Oblique Twist with Dumbbell",
    "Lying Flutter Kicks",
    "Side Crunch with Dumbbell",
    "Seated Leg Raises",
    "Cable Side Crunches",
    "Kettlebell Abs Press",
    "Cable Cross-Body Crunch",
    "Plank with Side Twist",
    "Kettlebell Sit-Up with Punch",
    "Medicine Ball Russian Twists with Hold",
    "Crunch with Leg Hold",
    "Hanging Leg Raise with Twist",
    "Seated Russian Twists",
    "Mountain Climbers with Leg Twist",
    "Box Crunches",
    "Barbell Russian Twist",
    "Kettlebell Russian Twists with Squeeze",
    "Kettlebell Leg Raise",
    "Resistance Band Sit-Up",
    "Leg Raise with Curl",
    "Plank with Alternate Arm Lift",
    "Straight Arm Plank",
    "Cable Woodchoppers with Squat",
    "Side Plank with Leg and Arm Lift",
    "Reverse Crunch with Twist",
    "Sit-Up to Russian Twist",
    "Medicine Ball Plank",
    "Side Plank with Toe Touch",
    "Incline Leg Raise",
    "Decline Sit-Up with Twist",
    "Knee Tucks on Ball",
    "Resistance Band Crunches",
    "Standing Resistance Band Oblique Twist",
    "Russian Twist with Weight Plate",
    "Side Plank with Resistance Band",
    "Bicycle Crunch with Hold",
    "Plank with Knee Crunch",
    "Weighted Side Plank",
    "Cable Woodchopper Twist",
    "Standing Ab Twist with Dumbbell",
    "Stability Ball Leg Raises",
    "Side Plank with Shoulder Touch",
    "Plank with Toe Tap",
    "Boxing Abs",
    "Abdominal Crunch on Ball",
    "Plank with Knee Tuck",
    "Kettlebell Oblique Twist",
    "Boxer Sit-Ups",
    "V-Sit with Medicine Ball",
    "Stability Ball Rollout with Hold",
    "Cable Oblique Twist",
    "Side-Lying Leg Raise",
    "Leg Lift with Ball Squeeze",
    "Standing Plank Reach",
    "Knee Raise with Hold",
    "Barbell Sit-Up",
    "Decline Leg Raise with Hold",
    "Ball Tuck with Plank",
    "Side Plank with Dumbbell Raise",
    "Crunch with Pause",
    "Mountain Climber with Medicine Ball",
    "Barbell Russian Twist with Squeeze",
    "Hanging Toe Touch",
    "Crunch with Pause at Peak",
    "Leg Raise with Pause",
    "Kettlebell Swing to Russian Twist",
    "Ab Wheel Rollout with Pause",
    "Sit-Up with Resistance Band",
    "Ball Leg Lift with Squeeze",
    "Side Plank with Knees to Chest",
    "Lying Ab Crunches",
    "Cable Trunk Rotation",
    "Crunch with Dumbbell Twist",
    "Plank with Leg to Elbow",
    "Straight-Leg Bicycle Crunches",
    "Side Plank Leg Lift with Band",
    "Ab Wheel Rollout with Knees",
    "Lateral Plank Walk",
    "Side Leg Raises with Dumbbells",
    "Plank with Toe Touch and Reach",
    "Hanging Knee Tuck",
    "Dumbbell Sit-Up to Press",
    "Machine Crunches",
    "Reverse Crunch with Dumbbell",
    "Seated Knee Tuck Crunch",
    "Flutter Kicks with Resistance Band",
    "Side Plank Crunch",
    "Bicycle Crunch with Weight",
    "Toe Touch with Resistance Band",
    "Side Plank with Weighted Hold",
    "Ab Circuit with Medicine Ball",
    "Dumbbell Russian Twists with Hold",
    "Side Plank with Leg Raise and Hold",
    "V-Up to Leg Raise",
    "Bicycle Crunch with Leg Hold",
    "Cross-Body Crunch",
    "Crunch with Side Twist",
    "Reverse Crunch with Resistance Band",
    "Stability Ball Crunch with Twist",
    "Side Plank with Arm and Leg Extension"
]

rumpf_uebungen = [
    "Plank",
    "Side Plank",
    "Russian Twists",
    "Mountain Climbers",
    "Leg Raises",
    "Reverse Crunches",
    "Sit-Ups",
    "Cable Crunches",
    "Ab Wheel Rollouts",
    "Hollow Body Hold",
    "Flutter Kicks",
    "V-Situps",
    "Oblique V-Ups",
    "Spider Plank",
    "Standing Oblique Crunches",
    "Standing Side Crunches",
    "Hanging Leg Raises",
    "Standing Leg Raise",
    "Kettlebell Russian Twists",
    "Lying Leg Raises",
    "Knee Tucks",
    "Decline Sit-Ups",
    "Decline Leg Raises",
    "V-Up",
    "Ab Rollouts",
    "Reverse Plank",
    "Side Plank with Leg Lift",
    "Side Plank with Hip Dips",
    "Superman Hold",
    "Kettlebell Windmill",
    "Lying Russian Twists",
    "Swiss Ball Rollouts",
    "Plank with Shoulder Taps",
    "Leg Raise with Twist",
    "Cable Woodchoppers",
    "Crunch with Resistance Band",
    "Swiss Ball Crunches",
    "Lying Flutter Kicks",
    "Side Plank Reach",
    "Bicycle Crunches",
    "Toe Touch Crunches",
    "Plank to Push-Up",
    "Standing Resistance Band Side Crunch",
    "Knee Tuck Crunches",
    "Decline Bench Crunches",
    "Lateral Leg Raises",
    "Leg Raise with Hold",
    "Cable Pallof Press",
    "Hanging Knee Raises",
    "Side Crunches",
    "Plank with Arm Lift",
    "Jackknife Sit-Ups",
    "Medicine Ball Russian Twists",
    "Mountain Climbers with Twist",
    "Bicycle Sit-Ups",
    "Medicine Ball Slams",
    "Barbell Rollouts",
    "Lateral Plank Walk",
    "Cable Oblique Twist",
    "Russian Twist with Plate",
    "V-Up to Leg Raise",
    "Leg Raise with Resistance Band",
    "Hanging Windshield Wipers",
    "Ab Circuit with Medicine Ball",
    "Lying Oblique Crunches",
    "Standing Cable Crunches",
    "Hanging Toe Touches",
    "Plank with Knee Tuck",
    "Standing Ab Twists with Dumbbell",
    "Reverse Crunch with Twist",
    "Seated Leg Raise",
    "Oblique V-Ups",
    "Ab Crunch with Dumbbell Twist",
    "Leg Raise with Curl",
    "Standing Leg Raise with Band",
    "Ab Rollout with Barbell",
    "Box Crunches",
    "Kettlebell Leg Raise",
    "Crunch with Leg Hold",
    "Kettlebell Sit-Up to Press",
    "Side Plank with Knee Crunch",
    "Weighted Sit-Ups",
    "Medicine Ball Oblique Twists",
    "Decline Crunches",
    "Ab Twist with Resistance Band",
    "Knee-In Crunches",
    "Stability Ball Leg Raises",
    "Plank with Reach",
    "Kettlebell Oblique Twist",
    "Seated Ab Crunch with Medicine Ball",
    "Alternating Toe Touches",
    "Cross-Body Crunch",
    "Plank with Leg Lift",
    "Ab Rollout with Stability Ball",
    "Side Plank with Weighted Hold",
    "Leg Raise with Twist and Hold",
    "Cable Reverse Crunches",
    "Crunch with Pause",
    "Hollow Body Roll",
    "Lateral Plank Reach",
    "Hanging Ab Twists",
    "Oblique Crunch with Dumbbell",
    "Boxer Sit-Ups",
    "Side Plank with Arm and Leg Raise",
    "Russian Twists with Hold",
    "Crunch with Exercise Ball",
    "Plank with Toe Tap",
    "Standing Leg Raise with Twist",
    "Ab Rollout to Plank",
    "Seated Knee Tuck Crunch",
    "Plank Reach Through",
    "Weighted Russian Twists",
    "Bicycle Crunch with Hold",
    "Straight Leg Raise with Hold",
    "Leg Lift with Twist",
    "Cable Woodchopper Twist",
    "Hanging Knee Tuck",
    "Reverse Crunch with Resistance Band",
    "Standing Leg Raise with Hold",
    "Plank with Knee Crunch",
    "Side Plank with Toe Touch",
    "Side Plank with Leg and Arm Lift",
    "Leg Raise to Plank",
    "Hanging Leg Raise with Twist",
    "Plank with Abduction",
    "Leg Raise with Pause",
    "Cross-Legged Crunches",
    "Plank with Knee Taps",
    "Lying Leg Raises with Band",
    "Barbell Sit-Up",
    "Leg Raise with Pause at Top",
    "Leg Raise with Band Resistance",
    "Abdominal Rollout with Stability Ball",
    "Mountain Climbers with Resistance Band",
    "Crunch with Dumbbell Hold",
    "Cable Side Crunches",
    "Sit-Up with Punch",
    "Leg Raise with Resistance Bands",
    "Oblique Crunch with Plate",
    "Ab Rollout with Resistance Band",
    "Russian Twist with Weight Plate",
    "Weighted Side Crunches",
    "Flutter Kicks with Resistance Band",
    "Kettlebell Sit-Up with Punch",
    "Medicine Ball Crunch",
    "Decline Sit-Ups with Hold",
    "Ab Wheel Rollout with Pause",
    "Box Crunches with Medicine Ball",
    "Seated Russian Twists with Dumbbell",
    "Lying Hip Thrusts",
    "Side Leg Raises with Resistance Band",
    "Leg Raise with Pause at Bottom",
    "Side Plank with Knee Tuck and Twist",
    "Medicine Ball Sit-Ups",
    "Weighted Ab Twist",
    "Lying Oblique Crunches with Weight",
    "Kettlebell Russian Twist with Hold",
    "Oblique V-Up with Leg Hold",
    "Weighted Crunches with Pause",
    "Ab Twist with Medicine Ball",
    "Leg Raise with Ankle Weights",
    "Side Plank with Oblique Reach",
    "Sit-Up with Kettlebell Swing",
    "Ab Twist with Resistance Band",
    "V-Ups with Medicine Ball",
    "Flutter Kicks with Weights",
    "Hanging Leg Raise with Hold",
    "Plank to Push-Up with Twist",
    "Ab Rollout with Pause at Top",
    "Russian Twist with Barbell",
    "Side Plank with Knee and Elbow Touch",
    "Plank with Leg and Arm Extension",
    "Leg Raise with Resistance Bands",
    "Knee Tuck to Chest",
    "Standing Resistance Band Crunch",
    "Kettlebell Rollout",
    "Crunch with Resistance Band",
    "Side Plank with Weighted Leg Lift",
    "Ab Rollout with Barbell",
    "Lying Down Russian Twists",
    "Plank with Lateral Reach",
    "Leg Raise to Crunch",
    "Side Plank with Arm Extension",
    "Seated Crunch with Band",
    "Resistance Band Russian Twist",
    "Cable Reverse Woodchopper",
    "Ab Rollouts with Stability Ball",
    "Hanging Windshield Wipers",
    "Plank with Alternate Leg Lift",
    "Lying Oblique Crunch with Hold",
    "Plank with Knee to Elbow",
    "Cable Trunk Rotation",
    "Standing Crunch with Dumbbells",
    "Hanging Leg Raise with Resistance Band",
    "Decline Russian Twists",
    "Ab Rollout with Resistance Band",
    "Seated Knee Tucks with Medicine Ball",
    "Side Plank with Heel Tap",
    "Standing Oblique Leg Raise",
    "Plank to Knee Crunch",
    "Side Plank with Knee Drive",
    "Hanging Knee Raises with Twist",
    "Cable Side Bends",
    "Lying Down Leg Raises with Weight",
    "Side Plank with Hip Flexion",
    "Side Leg Raise with Band",
    "Weighted V-Sit",
    "Standing Russian Twist with Band",
    "Russian Twist with Weight Plate",
    "Side Plank with Leg Extension"
]

eigengewicht_uebungen = [
    "Push-Ups",
    "Pull-Ups",
    "Chin-Ups",
    "Dips",
    "Bodyweight Squats",
    "Lunges",
    "Bulgarian Split Squats",
    "Pistol Squats",
    "Glute Bridges",
    "Plank",
    "Side Plank",
    "Mountain Climbers",
    "Jumping Jacks",
    "Jump Squats",
    "Box Jumps",
    "Bear Crawls",
    "Lateral Lunges",
    "Inchworms",
    "Leg Raises",
    "Flutter Kicks",
    "V-Ups",
    "Crunches",
    "Russian Twists",
    "Bicycle Crunches",
    "Superman Hold",
    "Leg Circles",
    "Triceps Dips",
    "Push-Up to Plank",
    "Plank with Shoulder Taps",
    "Plank to Push-Up",
    "Side Plank with Leg Lift",
    "Wall Sit",
    "Cossack Squats",
    "Clapping Push-Ups",
    "Triceps Push-Ups",
    "Dive Bomber Push-Ups",
    "Spider Plank",
    "Plank with Arm Lift",
    "Ab Wheel Rollouts",
    "Squat Jumps",
    "Single-Leg Glute Bridges",
    "Squat Pulse",
    "Tuck Jumps",
    "Handstand Push-Ups",
    "Frog Jumps",
    "Lunge Jumps",
    "Mountain Climbers with Twist",
    "Lateral Plank Walks",
    "Leg Raises with Hold",
    "V-Sits",
    "Knee Push-Ups",
    "Pike Push-Ups",
    "Wall Push-Ups",
    "Pistol Squat to Box",
    "Leg Raise to Plank",
    "Crunch with Twist",
    "Side Crunches",
    "Plank with Leg Lift",
    "Plank Reach Through",
    "Hollow Body Hold",
    "Standing Oblique Crunches",
    "Glute Kickbacks",
    "Reverse Lunges",
    "Jump Lunges",
    "Lying Leg Raises",
    "Seated Leg Raises",
    "Side Leg Raises",
    "Squat Hold",
    "Scorpion Push-Ups",
    "Push-Up to T",
    "Lying Flutter Kicks",
    "Inverted Rows",
    "Decline Push-Ups",
    "Incline Push-Ups",
    "Wide Push-Ups",
    "Diamond Push-Ups",
    "Archers Push-Ups",
    "Plank Jacks",
    "Side Plank with Arm Reach",
    "Lunge with Knee Drive",
    "Jumping Lunges",
    "Surrender Squats",
    "Crawling Push-Ups",
    "Tuck-Ups",
    "Leg Circles",
    "Bear Crawl Push-Ups",
    "Single-Leg Deadlifts",
    "Side Leg Circles",
    "High Knees",
    "Butt Kicks",
    "Hip Thrusts",
    "Hip Bridges with March",
    "Bear Crawl Shoulder Taps",
    "Hip Abduction",
    "Prisoner Squats",
    "High Plank with Leg Raise",
    "Spiderman Push-Ups",
    "Standing Calf Raises",
    "Squat with Jump",
    "Knee Tuck Jumps",
    "Plank with Knee to Elbow",
    "Front Kick to Crunch",
    "Reverse Crunch",
    "Standing Side Crunches",
    "Toe Touch Crunches",
    "Ab Rollouts with Resistance Band",
    "Decline Leg Raises",
    "Mountain Climbers with Push-Up",
    "Plank with Twist",
    "Back Extensions",
    "Lying Oblique Crunches",
    "Side Plank with Crunch",
    "Push-Up Plank",
    "Squat to Jump",
    "Leg Blasters",
    "Squat Holds with Pulse",
    "Crab Walk",
    "Tricep Dips with Leg Raise",
    "Mountain Climbers with Toe Tap",
    "Walking Lunges",
    "Reverse Lunge with Knee Drive",
    "Squat to Stand",
    "Plank with Cross Body Reach",
    "Squat with Kick",
    "Single-Leg Glute Bridge",
    "Inverted Leg Raises",
    "Walking Push-Ups",
    "Leg Raise Hold",
    "Jump Squats with Hold",
    "Push-Up with Shoulder Tap",
    "Squat to Calf Raise",
    "Superman Push-Ups",
    "Jump Lunges with Twist",
    "Plank with Hand Touch",
    "Wide Squat Hold",
    "Alternating Toe Touches",
    "Triceps Dips on Bench",
    "Step-Ups",
    "Wall Sit with Leg Lift",
    "Plank Jumps",
    "Bicycle Crunch with Hold",
    "Side Plank with Hip Dips",
    "Spider-Man Climbers",
    "Knee Tuck with Hold",
    "Side Lunge to Kick",
    "Squat with Pulse",
    "Glute Bridge March",
    "Squat to Reverse Lunge",
    "Side Plank with Rotation",
    "Plank with Arm Reach",
    "Leg Raise to Crunch",
    "Lateral Step-Ups",
    "Crossover Step-Ups",
    "Step-Up with Knee Raise",
    "Front Plank",
    "Wall Push-Up with Clap",
    "Climbing Plank",
    "Sphinx Push-Up",
    "Side Plank with Knee Tap",
    "Prisoner Squat Jumps",
    "Lying Leg Raise with Hip Thrust",
    "Knee Jumping Jacks",
    "Plank to Reverse Crunch",
    "Mountain Climbers with Elbow Tap",
    "Leg Kickback with Hold",
    "Backwards Lunge with Kick",
    "Side Plank with Toe Touch",
    "Hand Release Push-Up",
    "Jump Squat with 180 Turn",
    "Reverse Plank",
    "Plank with Reach and Tap",
    "Seated Leg Raise",
    "Push-Up to Plank Twist",
    "Knee Plank",
    "Wall Sits with Arm Circles",
    "Plank with Tap",
    "Squat Reach Jump",
    "Jumping Lateral Lunges",
    "Knee-Ins",
    "Alternating Lateral Plank",
    "Squat to Side Kick",
    "Split Squat",
    "Push-Up to Knee Drive",
    "Boxer Push-Ups",
    "Rotational Lunge",
    "Squat to Forward Lunge",
    "Skater Jumps",
    "Boxer Hold",
    "Single-Leg Push-Ups",
    "Diamond Sit-Ups",
    "Jumping High Knees",
    "Side-Lying Leg Raise",
    "Crunch with Leg Hold",
    "Jump Squats with 360 Turn",
    "Plank with Arm and Leg Lift",
    "Walking Plank",
    "Leg Blasters with Jumps",
    "Squat to Forward Punch",
    "Skater Jumps with Lateral Movement",
    "Bodyweight Squat to Side Kick",
    "Inverted Push-Ups",
    "Plyometric Push-Ups",
    "Squat Jump to Burpee",
    "Push-Up to Side Plank",
    "Knee Tuck to Jump",
    "Bear Crawl to Push-Up",
    "Lying Leg Circles",
    "Lateral Push-Up",
    "Bicycle Crunch with Twist",
    "Double Leg Lifts",
    "Side Kick with Knee Drive",
    "Wide Jumping Jacks",
    "Lunges with Reverse Lunge",
    "Bicycle Push-Ups",
    "Plank with Leg Extension"
]

kettlebell_uebungen = [
    "Kettlebell Swing",
    "Kettlebell Goblet Squat",
    "Kettlebell Clean and Press",
    "Kettlebell Snatch",
    "Kettlebell Turkish Get-Up",
    "Kettlebell Deadlift",
    "Kettlebell Sumo Deadlift",
    "Kettlebell Overhead Press",
    "Kettlebell Lunge",
    "Kettlebell Russian Twist",
    "Kettlebell Row",
    "Kettlebell Clean",
    "Kettlebell Push Press",
    "Kettlebell Thruster",
    "Kettlebell Windmill",
    "Kettlebell Front Squat",
    "Kettlebell Squat Clean",
    "Kettlebell Swing to Squat",
    "Kettlebell Single-Leg Deadlift",
    "Kettlebell High Pull",
    "Kettlebell Russian Kettlebell Swing",
    "Kettlebell Sumo Squat",
    "Kettlebell Figure 8",
    "Kettlebell Jump Squat",
    "Kettlebell Single-Arm Swing",
    "Kettlebell Squat and Press",
    "Kettlebell Halo",
    "Kettlebell Lateral Lunge",
    "Kettlebell Clean to Squat",
    "Kettlebell Snatch to Overhead Press",
    "Kettlebell Swing to Press",
    "Kettlebell Lateral Swing",
    "Kettlebell Reverse Lunge with Press",
    "Kettlebell Kettlebell Burpee",
    "Kettlebell Farmers Walk",
    "Kettlebell Plank Rows",
    "Kettlebell Rotational Press",
    "Kettlebell Plank Drag",
    "Kettlebell Split Squat",
    "Kettlebell Push-Up",
    "Kettlebell Step-Up",
    "Kettlebell Side Lunge",
    "Kettlebell Renegade Row",
    "Kettlebell Triceps Extension",
    "Kettlebell Bicep Curl",
    "Kettlebell Chest Press",
    "Kettlebell Reverse Lunge with Row",
    "Kettlebell Deadlift to Row",
    "Kettlebell Squat to Shoulder Press",
    "Kettlebell Plank Push-Up",
    "Kettlebell Sumo Squat to High Pull",
    "Kettlebell Windmill to Press",
    "Kettlebell Core Twist",
    "Kettlebell Jerk",
    "Kettlebell Clean and Jerk",
    "Kettlebell Deadlift to Shoulder Press",
    "Kettlebell Skater Squat",
    "Kettlebell Kettlebell Deadlift to Row",
    "Kettlebell Split Press",
    "Kettlebell Standing Chest Press",
    "Kettlebell Jumping Jack to Press",
    "Kettlebell Push Press",
    "Kettlebell Bicep Curl to Press",
    "Kettlebell Lateral Raise",
    "Kettlebell Ab Twist",
    "Kettlebell Reverse Squat",
    "Kettlebell Arm Bar",
    "Kettlebell Chest Fly",
    "Kettlebell Jump Lunge",
    "Kettlebell Standing Russian Twist",
    "Kettlebell TGU (Turkish Get-Up)",
    "Kettlebell Jump Squat to Press",
    "Kettlebell Shoulder Shrug",
    "Kettlebell Jerk and Push Press",
    "Kettlebell Half Snatch",
    "Kettlebell Clean and Front Squat",
    "Kettlebell Box Jump",
    "Kettlebell Lateral Step-Up",
    "Kettlebell Overhead Tricep Extension",
    "Kettlebell Overhead Hold",
    "Kettlebell Swing to Snatch",
    "Kettlebell Sumo Squat to Curl",
    "Kettlebell Glute Bridge Press",
    "Kettlebell Reverse Lunge to Press",
    "Kettlebell Weighted Walking Lunges",
    "Kettlebell Squat Jumps",
    "Kettlebell Reverse Grip Row",
    "Kettlebell Mountain Climbers",
    "Kettlebell Box Squat",
    "Kettlebell Shrugs",
    "Kettlebell Swings to Squat",
    "Kettlebell Renegade Push-Ups",
    "Kettlebell Ab Rollouts",
    "Kettlebell Single-Leg Press",
    "Kettlebell Squat with Hold",
    "Kettlebell Half Clean",
    "Kettlebell Squat Jumps to Snatch",
    "Kettlebell Double Snatch",
    "Kettlebell Sumo Deadlift to Squat",
    "Kettlebell Bear Crawl",
    "Kettlebell Leg Raise",
    "Kettlebell Overhead Squat",
    "Kettlebell Knee Drive with Squat",
    "Kettlebell Kettlebell Leg Press",
    "Kettlebell Biceps Curl to Squat",
    "Kettlebell Toe Touch",
    "Kettlebell Bear Squat",
    "Kettlebell High Knees",
    "Kettlebell Forward Lunge",
    "Kettlebell Plank with Shoulder Taps",
    "Kettlebell Side Press",
    "Kettlebell Jumping Lunges",
    "Kettlebell Kneeling Clean and Press",
    "Kettlebell Row to Renegade Row",
    "Kettlebell Squat to T-Push-Up",
    "Kettlebell Ab Twist with Hold",
    "Kettlebell Glute Kickback",
    "Kettlebell Box Jump to Squat",
    "Kettlebell Hip Thrusts",
    "Kettlebell Swing to High Pull",
    "Kettlebell Plank to Push-Up",
    "Kettlebell Lunge to Press",
    "Kettlebell Squat with Press",
    "Kettlebell Squat to Row",
    "Kettlebell Curl to Squat",
    "Kettlebell Russian Twist with Press",
    "Kettlebell Push Press to Squat",
    "Kettlebell Reverse Lunge to Row",
    "Kettlebell Side Raise to Overhead Press",
    "Kettlebell Clean and Deadlift",
    "Kettlebell Double Press",
    "Kettlebell Ab Pull-Through",
    "Kettlebell Tuck Jump",
    "Kettlebell Sumo Squat to Press",
    "Kettlebell Squat to Russian Twist",
    "Kettlebell Step-Up with Curl",
    "Kettlebell Sit-Up",
    "Kettlebell Lateral Raise to Front Raise",
    "Kettlebell Squat to Row to Press",
    "Kettlebell Box Squat to Press",
    "Kettlebell Squat and Hold",
    "Kettlebell Overhead Hold to Lunge",
    "Kettlebell Lateral Lunge to Press",
    "Kettlebell Lateral Plank Row",
    "Kettlebell Hip Thrust to Press",
    "Kettlebell Single-Arm Swing",
    "Kettlebell Plank Reach",
    "Kettlebell Mountain Climbers to Push-Up",
    "Kettlebell Bicep Curl with Press",
    "Kettlebell Lunge to Bicep Curl",
    "Kettlebell Plank with Kettlebell Pull",
    "Kettlebell High Pull to Squat",
    "Kettlebell Overhead Extension",
    "Kettlebell Crunches",
    "Kettlebell Sumo Deadlift with Row",
    "Kettlebell Shoulder Press",
    "Kettlebell Front Squat with Press",
    "Kettlebell Front Lunge to Squat",
    "Kettlebell Bicep Curl to Squat",
    "Kettlebell Cross-Body Snatch",
    "Kettlebell Back Lunge",
    "Kettlebell Shoulder Shrugs",
    "Kettlebell Glute Bridge Hold",
    "Kettlebell Burpee Press",
    "Kettlebell Overhead Triceps Extension",
    "Kettlebell Swings with Hold",
    "Kettlebell Jump Squats",
    "Kettlebell Overhead Walking Lunges",
    "Kettlebell Plank Rows to Press",
    "Kettlebell Squat to Curl to Press",
    "Kettlebell Push-Ups with Renegade Row",
    "Kettlebell Sumo Squat Hold",
    "Kettlebell Jump to Squat",
    "Kettlebell Russian Kettlebell Swing",
    "Kettlebell Turkish Get-Up with Press",
    "Kettlebell Overhead Squat with Snatch",
    "Kettlebell Lateral Lunge with Hold",
    "Kettlebell Windmill to Squat",
    "Kettlebell Squat and Hold",
    "Kettlebell Overhead Plank",
    "Kettlebell Squat to T-Push-Up",
    "Kettlebell Russian Swing to Snatch"
]

master_übung_list = []

master_übung_list.append(oberschenkel_uebungen)
master_übung_list.append(waden_uebungen)
master_übung_list.append(brust_uebungen)
master_übung_list.append(trizeps_uebungen)
master_übung_list.append(schulter_uebungen)
master_übung_list.append(bizeps_uebungen)
master_übung_list.append(ruecken_uebungen)
master_übung_list.append(bauch_uebungen)
master_übung_list.append(rumpf_uebungen)
master_übung_list.append(eigengewicht_uebungen)
master_übung_list.append(kettlebell_uebungen)


# def big_data():
#     for list_part in master_übung_list:
#         for ubung in list_part:
#             if not ÜbungenKrafttraining.objects.filter(name=ubung).exists():
#                 ÜbungenKrafttraining.objects.create(
#                 name=ubung,

#             )
#             print(f"Übung '{ubung}' wurde hinzugefügt RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.")
#         else:
#             print(f"Übung '{ubung}' existiert bereits.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")


def big_data():

    db_path = 'db.sqlite3'
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='workout_übungenkrafttraining';")
    result = cursor.fetchone()
    if not result:
        print("Fehler: Datenbanktabelle 'workout_übungenkrafttraining' nicht gefunden.")
        conn.close()
        return

    for list_part in master_übung_list:
        for ubung in list_part:
            # Überprüfen, ob die Übung bereits in der workout-Übungstabelle existiert
            cursor.execute("SELECT * FROM workout_übungenkrafttraining WHERE name = ?", (ubung,))
            existing_uebung = cursor.fetchone()
            
            if existing_uebung is None:
                # Übung hinzufügen, falls sie nicht existiert
                cursor.execute("INSERT INTO workout_übungenkrafttraining (name) VALUES (?)", (ubung,))
                conn.commit()
                print(f"Übung '{ubung}' wurde hinzugefügt RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.")
            else:
                print(f"Übung '{ubung}' existiert bereits. WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW")
    conn.close()

# Starte den Prozess
big_data()

# Schließe die Verbindung zur SQLite-Datenbank


big_data()



