# Generated by Django 5.1.4 on 2025-01-26 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="raw_food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="food.rawfoods"
            ),
        ),
    ]
